name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test
      - name: Run Cypress unit Tests
        run: npm run cypress:unit
